### ISSUE TITLE
Bug: uncaught exception -- args.method is None 

### ISSUE THREAD

**Issue by chovanecadam** [hansmach1ne/LFImap#38]
The `args.method` is undefined if `-M` is not specified and the placeholder (`--placeholder`,  `args.param`) is not part of the  URL. This causes the application to crash.

![bug](https://user-images.githubusercontent.com/23148601/232124710-bde2c92a-8330-48ed-8b92-64a302300909.png)

The issue lies in the following lines:

https://github.com/hansmach1ne/LFImap/blob/436ea01b5b81cef17f01684c221c453830f381fc/lfimap.py#L1623-L1632

One possible solution would be setting default method in the `optionsGroup.add_argument` call or rewriting the code in this fashion:

```python3
if (args.url and args.param in args.url): args.method = "GET" 
```

**Comment by hansmach1ne** [comment]
Thanks for taking an interest in LFImap. The snippet you pasted above is bad and will hopefully be fixed this week.

**Comment by hansmach1ne** [comment]
@chovanecadam

Implemented additional checks and default fallback method if it is not specified. Could you please git pull and check if everything works for you now?

**Comment by hansmach1ne** [comment]
I reopened this issue, because I noticed a few edge cases bugs with -R, -F modules. Will be fixing asap and test thoroughly new automatic parameter recognition feature, together with custom parameter specification with 'PWN'.
