### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by h3x0rz** [hansmach1ne/LFImap#39]
all requirements are installed but there is a problem with the tool 

![z31](https://user-images.githubusercontent.com/132023990/235344084-6f571587-6c4a-4f7c-a243-81c8ffa4cb33.png)

**Comment by hansmach1ne** [comment]
Hello,

Thank you for taking an interest in LFImap.
I will try to look into this problem. 

Currently, a source code cleanup and restructure is conducted, because the project is expanding pretty fast. Major 1.0 version will soon to be released with many new improvements and bug fixes.

**Comment by hansmach1ne** [comment]
@h3x0rz  Implemented automatic parameter recognition in the new commit https://github.com/hansmach1ne/LFImap/commit/a64cfbe8feff8a9a68404475115521b364e67b0d.

Could you please git pull and check if there is still any issues?

**Comment by hansmach1ne** [comment]
I reopened this issue, because I noticed a few edge cases bugs with -R, -F modules. Will be fixing asap and test thoroughly new automatic parameter recognition feature, together with custom parameter specification with 'PWN'.
