### ISSUE TITLE
'black' linter

### ISSUE THREAD

**Issue by nrathaus** [hansmach1ne/LFImap#54]
The code currently is written with somewhat weird tabbing/ missing of string concating, ' instead of ", may I recommend using `black` to just look more readable?

Here is a PR that will show you the difference (I just ran 'black' on the root folder)
https://github.com/hansmach1ne/LFImap/pull/53

**Comment by nrathaus** [comment]
Another thing worth working on is f-string from this:
```
print(
                    "\n"
                    + colors.lightblue("[i]")
                    + " Parsing URL ["
                    + str(iteration + 1)
                    + "/"
                    + str(len(config.parsedUrls))
                    + "]: '"
                    + url
                    + "'"
                )
```
To:
`print(f"\n{colors.lightblue('[i]')} Parsing URL [{str(iteration + 1)}/{str(len(config.parsedUrls))}]: '{url}'")`

**Comment by hansmach1ne** [comment]
https://github.com/hansmach1ne/LFImap/commit/98d3d974f062a11a715f7c7556ed84533e6600a7
