### ISSUE TITLE
Multiple fixes to `src/utils/parseurl.py`

### ISSUE THREAD

**Issue by nrathaus** [hansmach1ne/LFImap#65]
I created several PR that improve `src/utils/parseurl.py` as well as fix some minor issues

https://github.com/hansmach1ne/LFImap/pull/62
https://github.com/hansmach1ne/LFImap/pull/63
https://github.com/hansmach1ne/LFImap/pull/64

I made it into multiple PR to make it easier to integrate, also I made the commits separate so that you can cherry pick if you choose to do so

**Comment by hansmach1ne** [comment]
@nrathaus Thanks for all the commits. Will review all of them and likely integrate those.
Cheers!

**Comment by hansmach1ne** [comment]
Pushed, thanks bunch for these.
